server:
  port: 9577
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring.session.store-type: none
spring:
  main:
    banner-mode: "off"
#keycloak:
#  realm: sse
#  auth-server-url: http://localhost:8080/auth
#  ssl-required: external
#  resource: uno-api
#  public-client: true
