server:
  port: 9577
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring.session.store-type: none
spring:
  main:
    banner-mode: "off"
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456


cas:
  server-url-prefix: https://localhost:8443/cas
  server-login-url: https://localhost:8443/cas/login
  client-host-url: http://localhost:9577
  validation-type: cas3

