package com.bigdata.uno.repository;

import java.util.List;

import com.bigdata.uno.common.model.business.Business;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.jooq.QueryPart;
import org.springframework.stereotype.Repository;

import com.github.pagehelper.Page;
import com.bigdata.uno.repository.base.ListOption;
import com.bigdata.uno.repository.base.AbstractSqlProvider;
import com.bigdata.uno.repository.base.BaseRepository;
import com.bigdata.uno.repository.base.RepositoryGenerator;

/**
 * BusinessRepository generated by {@link RepositoryGenerator}
 *
 * @author bchen
 */
@Repository
public interface BusinessRepository extends BaseRepository<Business> {

    class SqlProvider extends AbstractSqlProvider {
        @Override
        public String table() {
            return "business";
        }
    }

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectById")
    Business selectById(Long id);

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectOne")
    Business selectOne(QueryPart where);

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectWhere")
    List<Business> selectWhere(QueryPart where);

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectAll")
    List<Business> selectAll();

    @Override
    @InsertProvider(type = SqlProvider.class, method = "insert")
    @Options(useGeneratedKeys = true)
    int insert(Business entity);

    @Override
    @UpdateProvider(type = SqlProvider.class, method = "updateByFields")
    int updateByFields(@Param("old") Business oldEntity,
                       @Param("new") Business newEntity);

    @Override
    @UpdateProvider(type = SqlProvider.class, method = "updateNotNullFields")
    int updateNotNullFields(Business entity);

    @Override
    @UpdateProvider(type = SqlProvider.class, method = "softDelete")
    int delete(Long id);

    @Override
    @UpdateProvider(type = SqlProvider.class, method = "softDeleteWhere")
    int deleteWhere(QueryPart where);

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectPage")
    Page<Business> selectPage(@Param("option") ListOption option,
                              @Param("pageNumKey") Long pageNum,
                              @Param("pageSizeKey") Long pageSize);

}
