package com.bigdata.uno.repository;

import java.util.List;

import com.bigdata.uno.common.model.project.ProjectPoJo;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.jooq.QueryPart;
import org.springframework.stereotype.Repository;

import com.github.pagehelper.Page;
import com.bigdata.uno.repository.base.ListOption;
import com.bigdata.uno.repository.base.AbstractSqlProvider;
import com.bigdata.uno.repository.base.BaseRepository;
import com.bigdata.uno.repository.base.RepositoryGenerator;

/**
 * ProjectRepository generated by {@link RepositoryGenerator}
 *
 * @author bchen
 */
@Repository
public interface ProjectRepository extends BaseRepository<ProjectPoJo> {

    class SqlProvider extends AbstractSqlProvider {
        @Override
        public String table() {
            return "project";
        }
    }

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectById")
    ProjectPoJo selectById(Long id);

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectOne")
    ProjectPoJo selectOne(QueryPart where);

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectWhere")
    List<ProjectPoJo> selectWhere(QueryPart where);

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectAll")
    List<ProjectPoJo> selectAll();

    @Override
    @InsertProvider(type = SqlProvider.class, method = "insert")
    @Options(useGeneratedKeys = true)
    int insert(ProjectPoJo entity);

    @Override
    @UpdateProvider(type = SqlProvider.class, method = "updateByFields")
    int updateByFields(@Param("old") ProjectPoJo oldEntity,
                       @Param("new") ProjectPoJo newEntity);

    @Override
    @UpdateProvider(type = SqlProvider.class, method = "updateNotNullFields")
    int updateNotNullFields(ProjectPoJo entity);

    @Override
    @UpdateProvider(type = SqlProvider.class, method = "softDelete")
    int delete(Long id);

    @Override
    @UpdateProvider(type = SqlProvider.class, method = "softDeleteWhere")
    int deleteWhere(QueryPart where);

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectPage")
    Page<ProjectPoJo> selectPage(@Param("option") ListOption option,
                                 @Param("pageNumKey") Long pageNum,
                                 @Param("pageSizeKey") Long pageSize);

}
