package com.bigdata.uno.repository;

import java.util.List;

import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.jooq.QueryPart;
import org.springframework.stereotype.Repository;

import com.github.pagehelper.Page;
import com.bigdata.uno.common.model.user.User;
import com.bigdata.uno.repository.base.ListOption;
import com.bigdata.uno.repository.base.AbstractSqlProvider;
import com.bigdata.uno.repository.base.BaseRepository;
import com.bigdata.uno.repository.base.RepositoryGenerator;

/**
 * UserRepository generated by {@link RepositoryGenerator}
 *
 * @author zaoshu
 */
@Repository
public interface UserRepository extends BaseRepository<User> {

    class SqlProvider extends AbstractSqlProvider {
        @Override
        public String table() {
            return "user";
        }
    }

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectById")
    User selectById(Long id);

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectOne")
    User selectOne(QueryPart where);

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectWhere")
    List<User> selectWhere(QueryPart where);

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectAll")
    List<User> selectAll();

    @Override
    @InsertProvider(type = SqlProvider.class, method = "insert")
    @Options(useGeneratedKeys = true)
    int insert(User entity);

    @Override
    @UpdateProvider(type = SqlProvider.class, method = "updateByFields")
    int updateByFields(@Param("old") User oldEntity,
                       @Param("new") User newEntity);

    @Override
    @UpdateProvider(type = SqlProvider.class, method = "softDelete")
    int delete(Long id);

    @Override
    @UpdateProvider(type = SqlProvider.class, method = "softDeleteWhere")
    int deleteWhere(QueryPart where);

    @Override
    @SelectProvider(type = SqlProvider.class, method = "selectPage")
    Page<User> selectPage(@Param("option") ListOption option,
                               @Param("pageNumKey") Long pageNum,
                               @Param("pageSizeKey") Long pageSize);

}
